language: node_js
node_js: "node"
git:
  depth: 3
addons:
  code_climate:
    repo_token: e66bc7e12082c61da0a2be29a3a5dd13f95ceafe14e0752c751a7d72d7fb3fa5
before_script:
  - apt-get install libstdc++6
  - npm install
  - npm install chai
  - npm install -g mocha
  - npm install -g istanbul
script:
  - istanbul cover _mocha --report lcovonly --print detail -- -R spec
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
